environment:

  matrix:

    # 32bit pythons
    - PYTHON: C:\Python27
      WDDK_INC_PATH: C:\WinDDK\7600.16385.1\inc\api;C:\WinDDK\7600.16385.1\inc\ddk;
      WDDK_LIB_PATH: C:\WinDDK\7600.16385.1\lib\wxp\i386;
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36
    - PYTHON: C:\Python37
    - PYTHON: C:\Python38

    # 64bit pythons
    - PYTHON: C:\Python27-x64
      WDDK_INC_PATH: C:\WinDDK\7600.16385.1\inc\api;C:\WinDDK\7600.16385.1\inc\ddk;
      WDDK_LIB_PATH: C:\WinDDK\7600.16385.1\lib\wlh\amd64;
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38-x64

install:
  # Setup the build environment
  - '%PYTHON%\python.exe -m pip install --disable-pip-version-check --user --upgrade pip'
  - '%PYTHON%\python.exe -m pip install --upgrade wheel'
  - '%PYTHON%\python.exe -m pip install --upgrade setuptools'

build: off

test_script:
  - ci\build_windows_wheels.cmd

after_test:
  - "echo 'done'"

artifacts:
  - path: wheelhouse\seabreeze-*
    name: wheel

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: M1DDbZLXnHTIW1xA7A6dkXCD6S4VCSP5QW2OiQUB4D2iZfGWNkOJSsGkZBHEfPL/
  artifact: wheel
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
